name: FirstFixYou
favicon: null
layout_spectrum: 0.4350760371889919
typography_spectrum: 0.5489201177842915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.14148306078277528
  lightness: 0.02626053267158568
  saturation: 0.5135158186312765
  rhythmicContrast: 0.48485680716112256
purpose: []
